name: atlas_emergency
description: Atlas Emergency Medical Services
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  
  # إدارة الحالة والتفضيلات
  provider: ^6.1.2
  shared_preferences: ^2.5.4
  
  # الخرائط والموقع
  flutter_map: ^7.0.0          # خريطة OpenStreetMap
  latlong2: ^0.9.1             # إحداثيات للخريطة
  geolocator: ^13.0.2          # تحديد الموقع
  permission_handler: ^11.4.0  # إدارة الأذونات
  
  # الاتصال بالخادم والويب
  http: ^1.2.2                  # استدعاءات API
  socket_io_client: ^3.0.2      # اتصال حي (WebSocket)
  
  # الإشعارات
  flutter_local_notifications: ^18.0.1  # إشعارات محلية
  timezone: ^0.9.4              # منطقة زمنية للإشعارات
  
  # تحميل الصور والعرض
  cached_network_image: ^3.4.1  # تحميل الصور مع تخزين مؤقت
  image_picker: ^1.1.2          # اختيار الصور من المعرض أو الكاميرا
  
  # واجهة المستخدم الإضافية
  url_launcher: ^6.3.1          # فتح الهاتف، الرسائل، الخرائط الخارجية
  shimmer: ^3.0.0               # تأثيرات تحميل لطيفة
  google_fonts: ^6.2.1          # خطوط جوجل لتحسين المظهر
  flutter_map_geojson2: ^1.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true   # مهم لتوليد ملفات الترجمة
  assets:
    - assets/data/morocco_hospitals.geojson  # أو الاسم الذي اخترته