# Generated by Django 4.2.30 on 2026-04-14 23:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('driver_phone', models.CharField(blank=True, db_column='phone', max_length=20, null=True)),
                ('is_online', models.BooleanField(blank=True, db_column='is_online', default=False, null=True)),
                ('current_latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=8, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=8, max_digits=11, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('patient_condition', models.TextField(blank=True)),
                ('eta_minutes', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('emergency_capacity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Responsable'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='dashboard.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cin', models.CharField(max_length=20, verbose_name='CIN')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('condition', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_treatment', 'In Treatment'), ('stable', 'Stable'), ('critical', 'Critical'), ('discharged', 'Discharged')], default='waiting', max_length=20)),
                ('admitted_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='dashboard.ambulance')),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.hospitaluser')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='dashboard.hospital')),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('common_symptoms', models.TextField()),
                ('treatment_protocol', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dashboard.hospital')),
            ],
            options={
                'db_table': 'medical_conditions',
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ambulance',
            name='destination_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_ambulances', to='dashboard.hospital'),
        ),
        migrations.CreateModel(
            name='BedAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('emergency', 'Emergency'), ('icu', 'ICU'), ('general', 'General Ward'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('covid', 'COVID-19 Isolation')], max_length=20)),
                ('total_beds', models.IntegerField(default=0)),
                ('available_beds', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='dashboard.hospital')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.hospitaluser')),
            ],
            options={
                'db_table': 'bed_availability',
                'unique_together': {('hospital', 'bed_type')},
            },
        ),
    ]
